// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// DeleteAPIKeyReader is a Reader for the DeleteAPIKey structure.
type DeleteAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteAPIKeyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 449:
		result := NewDeleteAPIKeyRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIKeyOK creates a DeleteAPIKeyOK with default headers values
func NewDeleteAPIKeyOK() *DeleteAPIKeyOK {
	return &DeleteAPIKeyOK{}
}

/*
DeleteAPIKeyOK describes a response with status code 200, with default header values.

The API key is deleted.
*/
type DeleteAPIKeyOK struct {
	Payload models.EmptyResponse
}

// IsSuccess returns true when this delete Api key o k response has a 2xx status code
func (o *DeleteAPIKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api key o k response has a 3xx status code
func (o *DeleteAPIKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api key o k response has a 4xx status code
func (o *DeleteAPIKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api key o k response has a 5xx status code
func (o *DeleteAPIKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api key o k response a status code equal to that given
func (o *DeleteAPIKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api key o k response
func (o *DeleteAPIKeyOK) Code() int {
	return 200
}

func (o *DeleteAPIKeyOK) Error() string {
	return fmt.Sprintf("[DELETE /users/auth/keys/{api_key_id}][%d] deleteApiKeyOK  %+v", 200, o.Payload)
}

func (o *DeleteAPIKeyOK) String() string {
	return fmt.Sprintf("[DELETE /users/auth/keys/{api_key_id}][%d] deleteApiKeyOK  %+v", 200, o.Payload)
}

func (o *DeleteAPIKeyOK) GetPayload() models.EmptyResponse {
	return o.Payload
}

func (o *DeleteAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIKeyNotFound creates a DeleteAPIKeyNotFound with default headers values
func NewDeleteAPIKeyNotFound() *DeleteAPIKeyNotFound {
	return &DeleteAPIKeyNotFound{}
}

/*
DeleteAPIKeyNotFound describes a response with status code 404, with default header values.

The {api_key_id} can't be found. (code: `api_keys.key_not_found`)
*/
type DeleteAPIKeyNotFound struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this delete Api key not found response has a 2xx status code
func (o *DeleteAPIKeyNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api key not found response has a 3xx status code
func (o *DeleteAPIKeyNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api key not found response has a 4xx status code
func (o *DeleteAPIKeyNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api key not found response has a 5xx status code
func (o *DeleteAPIKeyNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api key not found response a status code equal to that given
func (o *DeleteAPIKeyNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete Api key not found response
func (o *DeleteAPIKeyNotFound) Code() int {
	return 404
}

func (o *DeleteAPIKeyNotFound) Error() string {
	return fmt.Sprintf("[DELETE /users/auth/keys/{api_key_id}][%d] deleteApiKeyNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAPIKeyNotFound) String() string {
	return fmt.Sprintf("[DELETE /users/auth/keys/{api_key_id}][%d] deleteApiKeyNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAPIKeyNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *DeleteAPIKeyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIKeyRetryWith creates a DeleteAPIKeyRetryWith with default headers values
func NewDeleteAPIKeyRetryWith() *DeleteAPIKeyRetryWith {
	return &DeleteAPIKeyRetryWith{}
}

/*
DeleteAPIKeyRetryWith describes a response with status code 449, with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type DeleteAPIKeyRetryWith struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this delete Api key retry with response has a 2xx status code
func (o *DeleteAPIKeyRetryWith) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api key retry with response has a 3xx status code
func (o *DeleteAPIKeyRetryWith) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api key retry with response has a 4xx status code
func (o *DeleteAPIKeyRetryWith) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api key retry with response has a 5xx status code
func (o *DeleteAPIKeyRetryWith) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api key retry with response a status code equal to that given
func (o *DeleteAPIKeyRetryWith) IsCode(code int) bool {
	return code == 449
}

// Code gets the status code for the delete Api key retry with response
func (o *DeleteAPIKeyRetryWith) Code() int {
	return 449
}

func (o *DeleteAPIKeyRetryWith) Error() string {
	return fmt.Sprintf("[DELETE /users/auth/keys/{api_key_id}][%d] deleteApiKeyRetryWith  %+v", 449, o.Payload)
}

func (o *DeleteAPIKeyRetryWith) String() string {
	return fmt.Sprintf("[DELETE /users/auth/keys/{api_key_id}][%d] deleteApiKeyRetryWith  %+v", 449, o.Payload)
}

func (o *DeleteAPIKeyRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *DeleteAPIKeyRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
