// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// DeleteUserAPIKeysReader is a Reader for the DeleteUserAPIKeys structure.
type DeleteUserAPIKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserAPIKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUserAPIKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteUserAPIKeysNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 449:
		result := NewDeleteUserAPIKeysRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUserAPIKeysOK creates a DeleteUserAPIKeysOK with default headers values
func NewDeleteUserAPIKeysOK() *DeleteUserAPIKeysOK {
	return &DeleteUserAPIKeysOK{}
}

/*
DeleteUserAPIKeysOK describes a response with status code 200, with default header values.

The API key is deleted.
*/
type DeleteUserAPIKeysOK struct {
	Payload models.EmptyResponse
}

// IsSuccess returns true when this delete user Api keys o k response has a 2xx status code
func (o *DeleteUserAPIKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete user Api keys o k response has a 3xx status code
func (o *DeleteUserAPIKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete user Api keys o k response has a 4xx status code
func (o *DeleteUserAPIKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete user Api keys o k response has a 5xx status code
func (o *DeleteUserAPIKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete user Api keys o k response a status code equal to that given
func (o *DeleteUserAPIKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete user Api keys o k response
func (o *DeleteUserAPIKeysOK) Code() int {
	return 200
}

func (o *DeleteUserAPIKeysOK) Error() string {
	return fmt.Sprintf("[DELETE /users/{user_id}/auth/keys][%d] deleteUserApiKeysOK  %+v", 200, o.Payload)
}

func (o *DeleteUserAPIKeysOK) String() string {
	return fmt.Sprintf("[DELETE /users/{user_id}/auth/keys][%d] deleteUserApiKeysOK  %+v", 200, o.Payload)
}

func (o *DeleteUserAPIKeysOK) GetPayload() models.EmptyResponse {
	return o.Payload
}

func (o *DeleteUserAPIKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUserAPIKeysNotFound creates a DeleteUserAPIKeysNotFound with default headers values
func NewDeleteUserAPIKeysNotFound() *DeleteUserAPIKeysNotFound {
	return &DeleteUserAPIKeysNotFound{}
}

/*
DeleteUserAPIKeysNotFound describes a response with status code 404, with default header values.

The {user_id} can't be found. (code: `api_keys.user_not_found`)
*/
type DeleteUserAPIKeysNotFound struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this delete user Api keys not found response has a 2xx status code
func (o *DeleteUserAPIKeysNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete user Api keys not found response has a 3xx status code
func (o *DeleteUserAPIKeysNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete user Api keys not found response has a 4xx status code
func (o *DeleteUserAPIKeysNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete user Api keys not found response has a 5xx status code
func (o *DeleteUserAPIKeysNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete user Api keys not found response a status code equal to that given
func (o *DeleteUserAPIKeysNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete user Api keys not found response
func (o *DeleteUserAPIKeysNotFound) Code() int {
	return 404
}

func (o *DeleteUserAPIKeysNotFound) Error() string {
	return fmt.Sprintf("[DELETE /users/{user_id}/auth/keys][%d] deleteUserApiKeysNotFound  %+v", 404, o.Payload)
}

func (o *DeleteUserAPIKeysNotFound) String() string {
	return fmt.Sprintf("[DELETE /users/{user_id}/auth/keys][%d] deleteUserApiKeysNotFound  %+v", 404, o.Payload)
}

func (o *DeleteUserAPIKeysNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *DeleteUserAPIKeysNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUserAPIKeysRetryWith creates a DeleteUserAPIKeysRetryWith with default headers values
func NewDeleteUserAPIKeysRetryWith() *DeleteUserAPIKeysRetryWith {
	return &DeleteUserAPIKeysRetryWith{}
}

/*
DeleteUserAPIKeysRetryWith describes a response with status code 449, with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type DeleteUserAPIKeysRetryWith struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this delete user Api keys retry with response has a 2xx status code
func (o *DeleteUserAPIKeysRetryWith) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete user Api keys retry with response has a 3xx status code
func (o *DeleteUserAPIKeysRetryWith) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete user Api keys retry with response has a 4xx status code
func (o *DeleteUserAPIKeysRetryWith) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete user Api keys retry with response has a 5xx status code
func (o *DeleteUserAPIKeysRetryWith) IsServerError() bool {
	return false
}

// IsCode returns true when this delete user Api keys retry with response a status code equal to that given
func (o *DeleteUserAPIKeysRetryWith) IsCode(code int) bool {
	return code == 449
}

// Code gets the status code for the delete user Api keys retry with response
func (o *DeleteUserAPIKeysRetryWith) Code() int {
	return 449
}

func (o *DeleteUserAPIKeysRetryWith) Error() string {
	return fmt.Sprintf("[DELETE /users/{user_id}/auth/keys][%d] deleteUserApiKeysRetryWith  %+v", 449, o.Payload)
}

func (o *DeleteUserAPIKeysRetryWith) String() string {
	return fmt.Sprintf("[DELETE /users/{user_id}/auth/keys][%d] deleteUserApiKeysRetryWith  %+v", 449, o.Payload)
}

func (o *DeleteUserAPIKeysRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *DeleteUserAPIKeysRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
