// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// GetUserAPIKeyReader is a Reader for the GetUserAPIKey structure.
type GetUserAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetUserAPIKeyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserAPIKeyOK creates a GetUserAPIKeyOK with default headers values
func NewGetUserAPIKeyOK() *GetUserAPIKeyOK {
	return &GetUserAPIKeyOK{}
}

/*
GetUserAPIKeyOK describes a response with status code 200, with default header values.

The API key metadata is retrieved.
*/
type GetUserAPIKeyOK struct {
	Payload *models.APIKeyResponse
}

// IsSuccess returns true when this get user Api key o k response has a 2xx status code
func (o *GetUserAPIKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get user Api key o k response has a 3xx status code
func (o *GetUserAPIKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user Api key o k response has a 4xx status code
func (o *GetUserAPIKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user Api key o k response has a 5xx status code
func (o *GetUserAPIKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get user Api key o k response a status code equal to that given
func (o *GetUserAPIKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get user Api key o k response
func (o *GetUserAPIKeyOK) Code() int {
	return 200
}

func (o *GetUserAPIKeyOK) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/auth/keys/{api_key_id}][%d] getUserApiKeyOK  %+v", 200, o.Payload)
}

func (o *GetUserAPIKeyOK) String() string {
	return fmt.Sprintf("[GET /users/{user_id}/auth/keys/{api_key_id}][%d] getUserApiKeyOK  %+v", 200, o.Payload)
}

func (o *GetUserAPIKeyOK) GetPayload() *models.APIKeyResponse {
	return o.Payload
}

func (o *GetUserAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserAPIKeyNotFound creates a GetUserAPIKeyNotFound with default headers values
func NewGetUserAPIKeyNotFound() *GetUserAPIKeyNotFound {
	return &GetUserAPIKeyNotFound{}
}

/*
GetUserAPIKeyNotFound describes a response with status code 404, with default header values.

The {api_key_id} can't be found. (code: `api_keys.key_not_found`)
*/
type GetUserAPIKeyNotFound struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this get user Api key not found response has a 2xx status code
func (o *GetUserAPIKeyNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user Api key not found response has a 3xx status code
func (o *GetUserAPIKeyNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user Api key not found response has a 4xx status code
func (o *GetUserAPIKeyNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get user Api key not found response has a 5xx status code
func (o *GetUserAPIKeyNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get user Api key not found response a status code equal to that given
func (o *GetUserAPIKeyNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get user Api key not found response
func (o *GetUserAPIKeyNotFound) Code() int {
	return 404
}

func (o *GetUserAPIKeyNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/auth/keys/{api_key_id}][%d] getUserApiKeyNotFound  %+v", 404, o.Payload)
}

func (o *GetUserAPIKeyNotFound) String() string {
	return fmt.Sprintf("[GET /users/{user_id}/auth/keys/{api_key_id}][%d] getUserApiKeyNotFound  %+v", 404, o.Payload)
}

func (o *GetUserAPIKeyNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *GetUserAPIKeyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
