// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// ReAuthenticateReader is a Reader for the ReAuthenticate structure.
type ReAuthenticateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReAuthenticateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReAuthenticateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReAuthenticateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 449:
		result := NewReAuthenticateRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReAuthenticateOK creates a ReAuthenticateOK with default headers values
func NewReAuthenticateOK() *ReAuthenticateOK {
	return &ReAuthenticateOK{}
}

/*ReAuthenticateOK handles this case with default header values.

The authentication is successful and token is returned in the body of the response.
*/
type ReAuthenticateOK struct {
	Payload *models.ReAuthenticationResponse
}

func (o *ReAuthenticateOK) Error() string {
	return fmt.Sprintf("[POST /users/auth/reauthenticate][%d] reAuthenticateOK  %+v", 200, o.Payload)
}

func (o *ReAuthenticateOK) GetPayload() *models.ReAuthenticationResponse {
	return o.Payload
}

func (o *ReAuthenticateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReAuthenticationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReAuthenticateBadRequest creates a ReAuthenticateBadRequest with default headers values
func NewReAuthenticateBadRequest() *ReAuthenticateBadRequest {
	return &ReAuthenticateBadRequest{}
}

/*ReAuthenticateBadRequest handles this case with default header values.

The request is invalid. Specify a different request, then try again. (code: `api_keys.invalid_re_auth_credentials`)
*/
type ReAuthenticateBadRequest struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *ReAuthenticateBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/auth/reauthenticate][%d] reAuthenticateBadRequest  %+v", 400, o.Payload)
}

func (o *ReAuthenticateBadRequest) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *ReAuthenticateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReAuthenticateRetryWith creates a ReAuthenticateRetryWith with default headers values
func NewReAuthenticateRetryWith() *ReAuthenticateRetryWith {
	return &ReAuthenticateRetryWith{}
}

/*ReAuthenticateRetryWith handles this case with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type ReAuthenticateRetryWith struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *ReAuthenticateRetryWith) Error() string {
	return fmt.Sprintf("[POST /users/auth/reauthenticate][%d] reAuthenticateRetryWith  %+v", 449, o.Payload)
}

func (o *ReAuthenticateRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *ReAuthenticateRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
