// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/elastic/cloud-sdk-go/pkg/models"
)

// NewCreateExtensionParams creates a new CreateExtensionParams object
// with the default values initialized.
func NewCreateExtensionParams() *CreateExtensionParams {
	var ()
	return &CreateExtensionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateExtensionParamsWithTimeout creates a new CreateExtensionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateExtensionParamsWithTimeout(timeout time.Duration) *CreateExtensionParams {
	var ()
	return &CreateExtensionParams{

		timeout: timeout,
	}
}

// NewCreateExtensionParamsWithContext creates a new CreateExtensionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateExtensionParamsWithContext(ctx context.Context) *CreateExtensionParams {
	var ()
	return &CreateExtensionParams{

		Context: ctx,
	}
}

// NewCreateExtensionParamsWithHTTPClient creates a new CreateExtensionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateExtensionParamsWithHTTPClient(client *http.Client) *CreateExtensionParams {
	var ()
	return &CreateExtensionParams{
		HTTPClient: client,
	}
}

/*CreateExtensionParams contains all the parameters to send to the API endpoint
for the create extension operation typically these are written to a http.Request
*/
type CreateExtensionParams struct {

	/*Body
	  the data that creates the extension

	*/
	Body *models.CreateExtensionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create extension params
func (o *CreateExtensionParams) WithTimeout(timeout time.Duration) *CreateExtensionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create extension params
func (o *CreateExtensionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create extension params
func (o *CreateExtensionParams) WithContext(ctx context.Context) *CreateExtensionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create extension params
func (o *CreateExtensionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create extension params
func (o *CreateExtensionParams) WithHTTPClient(client *http.Client) *CreateExtensionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create extension params
func (o *CreateExtensionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create extension params
func (o *CreateExtensionParams) WithBody(body *models.CreateExtensionRequest) *CreateExtensionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create extension params
func (o *CreateExtensionParams) SetBody(body *models.CreateExtensionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateExtensionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
