// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListExtensionsParams creates a new ListExtensionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListExtensionsParams() *ListExtensionsParams {
	return &ListExtensionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListExtensionsParamsWithTimeout creates a new ListExtensionsParams object
// with the ability to set a timeout on a request.
func NewListExtensionsParamsWithTimeout(timeout time.Duration) *ListExtensionsParams {
	return &ListExtensionsParams{
		timeout: timeout,
	}
}

// NewListExtensionsParamsWithContext creates a new ListExtensionsParams object
// with the ability to set a context for a request.
func NewListExtensionsParamsWithContext(ctx context.Context) *ListExtensionsParams {
	return &ListExtensionsParams{
		Context: ctx,
	}
}

// NewListExtensionsParamsWithHTTPClient creates a new ListExtensionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListExtensionsParamsWithHTTPClient(client *http.Client) *ListExtensionsParams {
	return &ListExtensionsParams{
		HTTPClient: client,
	}
}

/* ListExtensionsParams contains all the parameters to send to the API endpoint
   for the list extensions operation.

   Typically these are written to a http.Request.
*/
type ListExtensionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list extensions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListExtensionsParams) WithDefaults() *ListExtensionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list extensions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListExtensionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list extensions params
func (o *ListExtensionsParams) WithTimeout(timeout time.Duration) *ListExtensionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list extensions params
func (o *ListExtensionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list extensions params
func (o *ListExtensionsParams) WithContext(ctx context.Context) *ListExtensionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list extensions params
func (o *ListExtensionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list extensions params
func (o *ListExtensionsParams) WithHTTPClient(client *http.Client) *ListExtensionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list extensions params
func (o *ListExtensionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListExtensionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
