linters:
  disable:
    - dupl
    - lll
    - gochecknoglobals
    - gochecknoinits
    - scopelint
    - funlen
    - wsl
    - gomnd
    - maligned
linters-settings:
  govet:
    check-shadowing: false

  gofmt:
    simplify: true
  
  golint:
    min-confidence: 0

  gocyclo:
    # minimal code complexity to report, 30 by default (we should lower it to around 15-17)
    min-complexity: 20

  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true

  misspell:
    locale: neutral

  goimports:
    local-prefixes: github.com/elastic/cloud-sdk-go

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: \*_test\.go
      linters:
        - gocritic
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocognit

output:
  format: tab

run:
  tests: false
  timeout: 10m
