// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package deployments_notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeploymentNotesParams creates a new GetDeploymentNotesParams object
// with the default values initialized.
func NewGetDeploymentNotesParams() *GetDeploymentNotesParams {
	var ()
	return &GetDeploymentNotesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeploymentNotesParamsWithTimeout creates a new GetDeploymentNotesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeploymentNotesParamsWithTimeout(timeout time.Duration) *GetDeploymentNotesParams {
	var ()
	return &GetDeploymentNotesParams{

		timeout: timeout,
	}
}

// NewGetDeploymentNotesParamsWithContext creates a new GetDeploymentNotesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeploymentNotesParamsWithContext(ctx context.Context) *GetDeploymentNotesParams {
	var ()
	return &GetDeploymentNotesParams{

		Context: ctx,
	}
}

// NewGetDeploymentNotesParamsWithHTTPClient creates a new GetDeploymentNotesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeploymentNotesParamsWithHTTPClient(client *http.Client) *GetDeploymentNotesParams {
	var ()
	return &GetDeploymentNotesParams{
		HTTPClient: client,
	}
}

/*GetDeploymentNotesParams contains all the parameters to send to the API endpoint
for the get deployment notes operation typically these are written to a http.Request
*/
type GetDeploymentNotesParams struct {

	/*DeploymentID
	  Identifier for the deployment

	*/
	DeploymentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get deployment notes params
func (o *GetDeploymentNotesParams) WithTimeout(timeout time.Duration) *GetDeploymentNotesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get deployment notes params
func (o *GetDeploymentNotesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get deployment notes params
func (o *GetDeploymentNotesParams) WithContext(ctx context.Context) *GetDeploymentNotesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get deployment notes params
func (o *GetDeploymentNotesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get deployment notes params
func (o *GetDeploymentNotesParams) WithHTTPClient(client *http.Client) *GetDeploymentNotesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get deployment notes params
func (o *GetDeploymentNotesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeploymentID adds the deploymentID to the get deployment notes params
func (o *GetDeploymentNotesParams) WithDeploymentID(deploymentID string) *GetDeploymentNotesParams {
	o.SetDeploymentID(deploymentID)
	return o
}

// SetDeploymentID adds the deploymentId to the get deployment notes params
func (o *GetDeploymentNotesParams) SetDeploymentID(deploymentID string) {
	o.DeploymentID = deploymentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeploymentNotesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deployment_id
	if err := r.SetPathParam("deployment_id", o.DeploymentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
