// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package clusters_apm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// ResyncApmClusterReader is a Reader for the ResyncApmCluster structure.
type ResyncApmClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResyncApmClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResyncApmClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 449:
		result := NewResyncApmClusterRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewResyncApmClusterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewResyncApmClusterOK creates a ResyncApmClusterOK with default headers values
func NewResyncApmClusterOK() *ResyncApmClusterOK {
	return &ResyncApmClusterOK{}
}

/*ResyncApmClusterOK handles this case with default header values.

The cluster resync operation executed successfully
*/
type ResyncApmClusterOK struct {
	Payload models.EmptyResponse
}

func (o *ResyncApmClusterOK) Error() string {
	return fmt.Sprintf("[POST /clusters/apm/{cluster_id}/_resync][%d] resyncApmClusterOK  %+v", 200, o.Payload)
}

func (o *ResyncApmClusterOK) GetPayload() models.EmptyResponse {
	return o.Payload
}

func (o *ResyncApmClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResyncApmClusterRetryWith creates a ResyncApmClusterRetryWith with default headers values
func NewResyncApmClusterRetryWith() *ResyncApmClusterRetryWith {
	return &ResyncApmClusterRetryWith{}
}

/*ResyncApmClusterRetryWith handles this case with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type ResyncApmClusterRetryWith struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *ResyncApmClusterRetryWith) Error() string {
	return fmt.Sprintf("[POST /clusters/apm/{cluster_id}/_resync][%d] resyncApmClusterRetryWith  %+v", 449, o.Payload)
}

func (o *ResyncApmClusterRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *ResyncApmClusterRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResyncApmClusterInternalServerError creates a ResyncApmClusterInternalServerError with default headers values
func NewResyncApmClusterInternalServerError() *ResyncApmClusterInternalServerError {
	return &ResyncApmClusterInternalServerError{}
}

/*ResyncApmClusterInternalServerError handles this case with default header values.

The cluster resync operation failed for cluster {cluster_id}. (code: `clusters.resync_failed`)
*/
type ResyncApmClusterInternalServerError struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *ResyncApmClusterInternalServerError) Error() string {
	return fmt.Sprintf("[POST /clusters/apm/{cluster_id}/_resync][%d] resyncApmClusterInternalServerError  %+v", 500, o.Payload)
}

func (o *ResyncApmClusterInternalServerError) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *ResyncApmClusterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
