// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// MigrateDeploymentReader is a Reader for the MigrateDeployment structure.
type MigrateDeploymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MigrateDeploymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMigrateDeploymentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMigrateDeploymentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewMigrateDeploymentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMigrateDeploymentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMigrateDeploymentOK creates a MigrateDeploymentOK with default headers values
func NewMigrateDeploymentOK() *MigrateDeploymentOK {
	return &MigrateDeploymentOK{}
}

/*MigrateDeploymentOK handles this case with default header values.

The request was valid and the deployment can be migrated to the template with the provided id.
*/
type MigrateDeploymentOK struct {
	Payload *models.DeploymentTemplateMigrateResponse
}

func (o *MigrateDeploymentOK) Error() string {
	return fmt.Sprintf("[POST /deployments/{deployment_id}/_migrate][%d] migrateDeploymentOK  %+v", 200, o.Payload)
}

func (o *MigrateDeploymentOK) GetPayload() *models.DeploymentTemplateMigrateResponse {
	return o.Payload
}

func (o *MigrateDeploymentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeploymentTemplateMigrateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMigrateDeploymentBadRequest creates a MigrateDeploymentBadRequest with default headers values
func NewMigrateDeploymentBadRequest() *MigrateDeploymentBadRequest {
	return &MigrateDeploymentBadRequest{}
}

/*MigrateDeploymentBadRequest handles this case with default header values.

The deployment cannot be successfully migrated to the template with the provided id.
*/
type MigrateDeploymentBadRequest struct {
	Payload *models.BasicFailedReply
}

func (o *MigrateDeploymentBadRequest) Error() string {
	return fmt.Sprintf("[POST /deployments/{deployment_id}/_migrate][%d] migrateDeploymentBadRequest  %+v", 400, o.Payload)
}

func (o *MigrateDeploymentBadRequest) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *MigrateDeploymentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMigrateDeploymentUnauthorized creates a MigrateDeploymentUnauthorized with default headers values
func NewMigrateDeploymentUnauthorized() *MigrateDeploymentUnauthorized {
	return &MigrateDeploymentUnauthorized{}
}

/*MigrateDeploymentUnauthorized handles this case with default header values.

You are not authorized to perform this action.
*/
type MigrateDeploymentUnauthorized struct {
	Payload *models.BasicFailedReply
}

func (o *MigrateDeploymentUnauthorized) Error() string {
	return fmt.Sprintf("[POST /deployments/{deployment_id}/_migrate][%d] migrateDeploymentUnauthorized  %+v", 401, o.Payload)
}

func (o *MigrateDeploymentUnauthorized) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *MigrateDeploymentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMigrateDeploymentNotFound creates a MigrateDeploymentNotFound with default headers values
func NewMigrateDeploymentNotFound() *MigrateDeploymentNotFound {
	return &MigrateDeploymentNotFound{}
}

/*MigrateDeploymentNotFound handles this case with default header values.

The Deployment specified by {deployment_id} cannot be found. (code: `deployments.deployment_not_found`)
*/
type MigrateDeploymentNotFound struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *MigrateDeploymentNotFound) Error() string {
	return fmt.Sprintf("[POST /deployments/{deployment_id}/_migrate][%d] migrateDeploymentNotFound  %+v", 404, o.Payload)
}

func (o *MigrateDeploymentNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *MigrateDeploymentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
