// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package platform_configuration_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInstanceConfigurationsParams creates a new GetInstanceConfigurationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstanceConfigurationsParams() *GetInstanceConfigurationsParams {
	return &GetInstanceConfigurationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstanceConfigurationsParamsWithTimeout creates a new GetInstanceConfigurationsParams object
// with the ability to set a timeout on a request.
func NewGetInstanceConfigurationsParamsWithTimeout(timeout time.Duration) *GetInstanceConfigurationsParams {
	return &GetInstanceConfigurationsParams{
		timeout: timeout,
	}
}

// NewGetInstanceConfigurationsParamsWithContext creates a new GetInstanceConfigurationsParams object
// with the ability to set a context for a request.
func NewGetInstanceConfigurationsParamsWithContext(ctx context.Context) *GetInstanceConfigurationsParams {
	return &GetInstanceConfigurationsParams{
		Context: ctx,
	}
}

// NewGetInstanceConfigurationsParamsWithHTTPClient creates a new GetInstanceConfigurationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstanceConfigurationsParamsWithHTTPClient(client *http.Client) *GetInstanceConfigurationsParams {
	return &GetInstanceConfigurationsParams{
		HTTPClient: client,
	}
}

/* GetInstanceConfigurationsParams contains all the parameters to send to the API endpoint
   for the get instance configurations operation.

   Typically these are written to a http.Request.
*/
type GetInstanceConfigurationsParams struct {

	/* ShowDeleted.

	   If true, instance configurations marked for deletions are also returned. Otherwise, only instance configurations not marked for deletion are returned
	*/
	ShowDeleted *bool

	/* ShowMaxZones.

	   If true, will populate the max_zones field of the instance configurations.
	*/
	ShowMaxZones *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get instance configurations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstanceConfigurationsParams) WithDefaults() *GetInstanceConfigurationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get instance configurations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstanceConfigurationsParams) SetDefaults() {
	var (
		showMaxZonesDefault = bool(false)
	)

	val := GetInstanceConfigurationsParams{
		ShowMaxZones: &showMaxZonesDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get instance configurations params
func (o *GetInstanceConfigurationsParams) WithTimeout(timeout time.Duration) *GetInstanceConfigurationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instance configurations params
func (o *GetInstanceConfigurationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instance configurations params
func (o *GetInstanceConfigurationsParams) WithContext(ctx context.Context) *GetInstanceConfigurationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instance configurations params
func (o *GetInstanceConfigurationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instance configurations params
func (o *GetInstanceConfigurationsParams) WithHTTPClient(client *http.Client) *GetInstanceConfigurationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instance configurations params
func (o *GetInstanceConfigurationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithShowDeleted adds the showDeleted to the get instance configurations params
func (o *GetInstanceConfigurationsParams) WithShowDeleted(showDeleted *bool) *GetInstanceConfigurationsParams {
	o.SetShowDeleted(showDeleted)
	return o
}

// SetShowDeleted adds the showDeleted to the get instance configurations params
func (o *GetInstanceConfigurationsParams) SetShowDeleted(showDeleted *bool) {
	o.ShowDeleted = showDeleted
}

// WithShowMaxZones adds the showMaxZones to the get instance configurations params
func (o *GetInstanceConfigurationsParams) WithShowMaxZones(showMaxZones *bool) *GetInstanceConfigurationsParams {
	o.SetShowMaxZones(showMaxZones)
	return o
}

// SetShowMaxZones adds the showMaxZones to the get instance configurations params
func (o *GetInstanceConfigurationsParams) SetShowMaxZones(showMaxZones *bool) {
	o.ShowMaxZones = showMaxZones
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstanceConfigurationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ShowDeleted != nil {

		// query param show_deleted
		var qrShowDeleted bool

		if o.ShowDeleted != nil {
			qrShowDeleted = *o.ShowDeleted
		}
		qShowDeleted := swag.FormatBool(qrShowDeleted)
		if qShowDeleted != "" {

			if err := r.SetQueryParam("show_deleted", qShowDeleted); err != nil {
				return err
			}
		}
	}

	if o.ShowMaxZones != nil {

		// query param show_max_zones
		var qrShowMaxZones bool

		if o.ShowMaxZones != nil {
			qrShowMaxZones = *o.ShowMaxZones
		}
		qShowMaxZones := swag.FormatBool(qrShowMaxZones)
		if qShowMaxZones != "" {

			if err := r.SetQueryParam("show_max_zones", qShowMaxZones); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
