// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package platform_configuration_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new platform configuration instances API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for platform configuration instances API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateInstanceConfiguration creates instance configuration

Create instance configuration and return the auto-generated ID.
*/
func (a *Client) CreateInstanceConfiguration(params *CreateInstanceConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*CreateInstanceConfigurationCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateInstanceConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "create-instance-configuration",
		Method:             "POST",
		PathPattern:        "/platform/configuration/instances",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateInstanceConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateInstanceConfigurationCreated), nil

}

/*
DeleteInstanceConfiguration deletes a instance configuration

Delete the instance configuration with the given id.
*/
func (a *Client) DeleteInstanceConfiguration(params *DeleteInstanceConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteInstanceConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteInstanceConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "delete-instance-configuration",
		Method:             "DELETE",
		PathPattern:        "/platform/configuration/instances/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteInstanceConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteInstanceConfigurationOK), nil

}

/*
GetInstanceConfiguration gets instance configuration

Get instance configuration by id.
*/
func (a *Client) GetInstanceConfiguration(params *GetInstanceConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*GetInstanceConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetInstanceConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get-instance-configuration",
		Method:             "GET",
		PathPattern:        "/platform/configuration/instances/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInstanceConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetInstanceConfigurationOK), nil

}

/*
GetInstanceConfigurations gets instance configurations

Get instance configurations.
*/
func (a *Client) GetInstanceConfigurations(params *GetInstanceConfigurationsParams, authInfo runtime.ClientAuthInfoWriter) (*GetInstanceConfigurationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetInstanceConfigurationsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get-instance-configurations",
		Method:             "GET",
		PathPattern:        "/platform/configuration/instances",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInstanceConfigurationsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetInstanceConfigurationsOK), nil

}

/*
SetInstanceConfiguration sets instance configuration

Creates or updates an instance configuration.
*/
func (a *Client) SetInstanceConfiguration(params *SetInstanceConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*SetInstanceConfigurationOK, *SetInstanceConfigurationCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSetInstanceConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "set-instance-configuration",
		Method:             "PUT",
		PathPattern:        "/platform/configuration/instances/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SetInstanceConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *SetInstanceConfigurationOK:
		return value, nil, nil
	case *SetInstanceConfigurationCreated:
		return nil, value, nil
	}
	return nil, nil, nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
