// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package deployments_ip_filtering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// GetIPFilterRulesetsReader is a Reader for the GetIPFilterRulesets structure.
type GetIPFilterRulesetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIPFilterRulesetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIPFilterRulesetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetIPFilterRulesetsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetIPFilterRulesetsOK creates a GetIPFilterRulesetsOK with default headers values
func NewGetIPFilterRulesetsOK() *GetIPFilterRulesetsOK {
	return &GetIPFilterRulesetsOK{}
}

/*GetIPFilterRulesetsOK handles this case with default header values.

The IP filter rulesets for the user were successfully returned
*/
type GetIPFilterRulesetsOK struct {
	Payload *models.IPFilterRulesets
}

func (o *GetIPFilterRulesetsOK) Error() string {
	return fmt.Sprintf("[GET /deployments/ip-filtering/rulesets][%d] getIpFilterRulesetsOK  %+v", 200, o.Payload)
}

func (o *GetIPFilterRulesetsOK) GetPayload() *models.IPFilterRulesets {
	return o.Payload
}

func (o *GetIPFilterRulesetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IPFilterRulesets)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIPFilterRulesetsInternalServerError creates a GetIPFilterRulesetsInternalServerError with default headers values
func NewGetIPFilterRulesetsInternalServerError() *GetIPFilterRulesetsInternalServerError {
	return &GetIPFilterRulesetsInternalServerError{}
}

/*GetIPFilterRulesetsInternalServerError handles this case with default header values.

The request execution failed (code: 'ip_filtering.request_execution_failed')
*/
type GetIPFilterRulesetsInternalServerError struct {
	Payload *models.BasicFailedReply
}

func (o *GetIPFilterRulesetsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /deployments/ip-filtering/rulesets][%d] getIpFilterRulesetsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetIPFilterRulesetsInternalServerError) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *GetIPFilterRulesetsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
