// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateAPIKeyRequest The request payload that creates the API keys.
//
// swagger:model CreateApiKeyRequest
type CreateAPIKeyRequest struct {

	// API key description. Useful if there are multiple keys
	// Required: true
	Description *string `json:"description"`

	// The optional expiration for the API key, provided as a duration (ex: '1d', '3h')
	Expiration string `json:"expiration,omitempty"`

	// The optional roles for the API key. Takes the role of the creator if not specified. Currently unavailable in self-hosted ECE.
	RoleAssignments *RoleAssignments `json:"role_assignments,omitempty"`
}

// Validate validates this create Api key request
func (m *CreateAPIKeyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoleAssignments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateAPIKeyRequest) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *CreateAPIKeyRequest) validateRoleAssignments(formats strfmt.Registry) error {
	if swag.IsZero(m.RoleAssignments) { // not required
		return nil
	}

	if m.RoleAssignments != nil {
		if err := m.RoleAssignments.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role_assignments")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role_assignments")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create Api key request based on the context it is used
func (m *CreateAPIKeyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRoleAssignments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateAPIKeyRequest) contextValidateRoleAssignments(ctx context.Context, formats strfmt.Registry) error {

	if m.RoleAssignments != nil {
		if err := m.RoleAssignments.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role_assignments")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role_assignments")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateAPIKeyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAPIKeyRequest) UnmarshalBinary(b []byte) error {
	var res CreateAPIKeyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
