// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeploymentSettings Additional configuration about the current deployment object.
//
// swagger:model DeploymentSettings
type DeploymentSettings struct {

	// Logging and monitoring settings for this deployment
	Observability *DeploymentObservabilitySettings `json:"observability,omitempty"`

	// The traffic filter rulesets for this deployment.
	TrafficFilterSettings *TrafficFilterSettings `json:"traffic_filter_settings,omitempty"`
}

// Validate validates this deployment settings
func (m *DeploymentSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateObservability(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrafficFilterSettings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeploymentSettings) validateObservability(formats strfmt.Registry) error {
	if swag.IsZero(m.Observability) { // not required
		return nil
	}

	if m.Observability != nil {
		if err := m.Observability.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("observability")
			}
			return err
		}
	}

	return nil
}

func (m *DeploymentSettings) validateTrafficFilterSettings(formats strfmt.Registry) error {
	if swag.IsZero(m.TrafficFilterSettings) { // not required
		return nil
	}

	if m.TrafficFilterSettings != nil {
		if err := m.TrafficFilterSettings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic_filter_settings")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this deployment settings based on the context it is used
func (m *DeploymentSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateObservability(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTrafficFilterSettings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeploymentSettings) contextValidateObservability(ctx context.Context, formats strfmt.Registry) error {

	if m.Observability != nil {
		if err := m.Observability.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("observability")
			}
			return err
		}
	}

	return nil
}

func (m *DeploymentSettings) contextValidateTrafficFilterSettings(ctx context.Context, formats strfmt.Registry) error {

	if m.TrafficFilterSettings != nil {
		if err := m.TrafficFilterSettings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("traffic_filter_settings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeploymentSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeploymentSettings) UnmarshalBinary(b []byte) error {
	var res DeploymentSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
