// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlatformResourcesSummary Information about resources.
//
// swagger:model PlatformResourcesSummary
type PlatformResourcesSummary struct {

	// Number of accounts
	// Required: true
	AccountCount *int32 `json:"account_count"`

	// Number of available resources
	// Required: true
	AvailableCount *int32 `json:"available_count"`

	// Whether all resources are healthy
	// Required: true
	Healthy *bool `json:"healthy"`

	// Minimum number of available resources
	// Required: true
	MinimumAvailableCount *int32 `json:"minimum_available_count"`

	// Number of missing resources
	// Required: true
	MissingCount *int32 `json:"missing_count"`

	// Number of used resources
	// Required: true
	UsedCount *int32 `json:"used_count"`
}

// Validate validates this platform resources summary
func (m *PlatformResourcesSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailableCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHealthy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinimumAvailableCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMissingCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsedCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlatformResourcesSummary) validateAccountCount(formats strfmt.Registry) error {

	if err := validate.Required("account_count", "body", m.AccountCount); err != nil {
		return err
	}

	return nil
}

func (m *PlatformResourcesSummary) validateAvailableCount(formats strfmt.Registry) error {

	if err := validate.Required("available_count", "body", m.AvailableCount); err != nil {
		return err
	}

	return nil
}

func (m *PlatformResourcesSummary) validateHealthy(formats strfmt.Registry) error {

	if err := validate.Required("healthy", "body", m.Healthy); err != nil {
		return err
	}

	return nil
}

func (m *PlatformResourcesSummary) validateMinimumAvailableCount(formats strfmt.Registry) error {

	if err := validate.Required("minimum_available_count", "body", m.MinimumAvailableCount); err != nil {
		return err
	}

	return nil
}

func (m *PlatformResourcesSummary) validateMissingCount(formats strfmt.Registry) error {

	if err := validate.Required("missing_count", "body", m.MissingCount); err != nil {
		return err
	}

	return nil
}

func (m *PlatformResourcesSummary) validateUsedCount(formats strfmt.Registry) error {

	if err := validate.Required("used_count", "body", m.UsedCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this platform resources summary based on context it is used
func (m *PlatformResourcesSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlatformResourcesSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformResourcesSummary) UnmarshalBinary(b []byte) error {
	var res PlatformResourcesSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
