// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserSecurity A user's security information
//
// swagger:model UserSecurity
type UserSecurity struct {

	// The user's elevated permission status
	ElevatedPermissions *ElevatedPermissions `json:"elevated_permissions,omitempty"`

	// True if the user is enabled
	Enabled *bool `json:"enabled,omitempty"`

	// The user's password. Only used when modifying a user.
	Password string `json:"password,omitempty"`

	// The distinct set of permissions allowed by the user's roles. These correspond to operationId values in the OpenAPI definition.
	Permissions []string `json:"permissions,omitempty"`

	// The set of roles assigned to a user
	Roles []string `json:"roles,omitempty"`

	// The user's security realm
	SecurityRealm *UserSecurityRealm `json:"security_realm,omitempty"`
}

// Validate validates this user security
func (m *UserSecurity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateElevatedPermissions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurityRealm(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserSecurity) validateElevatedPermissions(formats strfmt.Registry) error {
	if swag.IsZero(m.ElevatedPermissions) { // not required
		return nil
	}

	if m.ElevatedPermissions != nil {
		if err := m.ElevatedPermissions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("elevated_permissions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("elevated_permissions")
			}
			return err
		}
	}

	return nil
}

func (m *UserSecurity) validateSecurityRealm(formats strfmt.Registry) error {
	if swag.IsZero(m.SecurityRealm) { // not required
		return nil
	}

	if m.SecurityRealm != nil {
		if err := m.SecurityRealm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("security_realm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("security_realm")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this user security based on the context it is used
func (m *UserSecurity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateElevatedPermissions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSecurityRealm(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserSecurity) contextValidateElevatedPermissions(ctx context.Context, formats strfmt.Registry) error {

	if m.ElevatedPermissions != nil {
		if err := m.ElevatedPermissions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("elevated_permissions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("elevated_permissions")
			}
			return err
		}
	}

	return nil
}

func (m *UserSecurity) contextValidateSecurityRealm(ctx context.Context, formats strfmt.Registry) error {

	if m.SecurityRealm != nil {
		if err := m.SecurityRealm.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("security_realm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("security_realm")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserSecurity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserSecurity) UnmarshalBinary(b []byte) error {
	var res UserSecurity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
