// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package clusters_kibana

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// StopKibanaClusterInstancesReader is a Reader for the StopKibanaClusterInstances structure.
type StopKibanaClusterInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopKibanaClusterInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewStopKibanaClusterInstancesAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewStopKibanaClusterInstancesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewStopKibanaClusterInstancesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 449:
		result := NewStopKibanaClusterInstancesRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStopKibanaClusterInstancesAccepted creates a StopKibanaClusterInstancesAccepted with default headers values
func NewStopKibanaClusterInstancesAccepted() *StopKibanaClusterInstancesAccepted {
	return &StopKibanaClusterInstancesAccepted{}
}

/*StopKibanaClusterInstancesAccepted handles this case with default header values.

The stop command was issued successfully, use the "GET" command on the /{cluster_id} resource to monitor progress
*/
type StopKibanaClusterInstancesAccepted struct {
	Payload *models.ClusterCommandResponse
}

func (o *StopKibanaClusterInstancesAccepted) Error() string {
	return fmt.Sprintf("[POST /clusters/kibana/{cluster_id}/instances/{instance_ids}/_stop][%d] stopKibanaClusterInstancesAccepted  %+v", 202, o.Payload)
}

func (o *StopKibanaClusterInstancesAccepted) GetPayload() *models.ClusterCommandResponse {
	return o.Payload
}

func (o *StopKibanaClusterInstancesAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterCommandResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopKibanaClusterInstancesForbidden creates a StopKibanaClusterInstancesForbidden with default headers values
func NewStopKibanaClusterInstancesForbidden() *StopKibanaClusterInstancesForbidden {
	return &StopKibanaClusterInstancesForbidden{}
}

/*StopKibanaClusterInstancesForbidden handles this case with default header values.

The stop command was prohibited for the given cluster. (code: `clusters.command_prohibited`)
*/
type StopKibanaClusterInstancesForbidden struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *StopKibanaClusterInstancesForbidden) Error() string {
	return fmt.Sprintf("[POST /clusters/kibana/{cluster_id}/instances/{instance_ids}/_stop][%d] stopKibanaClusterInstancesForbidden  %+v", 403, o.Payload)
}

func (o *StopKibanaClusterInstancesForbidden) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *StopKibanaClusterInstancesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopKibanaClusterInstancesNotFound creates a StopKibanaClusterInstancesNotFound with default headers values
func NewStopKibanaClusterInstancesNotFound() *StopKibanaClusterInstancesNotFound {
	return &StopKibanaClusterInstancesNotFound{}
}

/*StopKibanaClusterInstancesNotFound handles this case with default header values.

* The cluster specified by {cluster_id} cannot be found. (code: `clusters.cluster_not_found`)
* One or more of the instances specified at {instance_ids} could not be found. (code: `clusters.instances_not_found`)
 */
type StopKibanaClusterInstancesNotFound struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *StopKibanaClusterInstancesNotFound) Error() string {
	return fmt.Sprintf("[POST /clusters/kibana/{cluster_id}/instances/{instance_ids}/_stop][%d] stopKibanaClusterInstancesNotFound  %+v", 404, o.Payload)
}

func (o *StopKibanaClusterInstancesNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *StopKibanaClusterInstancesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopKibanaClusterInstancesRetryWith creates a StopKibanaClusterInstancesRetryWith with default headers values
func NewStopKibanaClusterInstancesRetryWith() *StopKibanaClusterInstancesRetryWith {
	return &StopKibanaClusterInstancesRetryWith{}
}

/*StopKibanaClusterInstancesRetryWith handles this case with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type StopKibanaClusterInstancesRetryWith struct {
	/*The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *StopKibanaClusterInstancesRetryWith) Error() string {
	return fmt.Sprintf("[POST /clusters/kibana/{cluster_id}/instances/{instance_ids}/_stop][%d] stopKibanaClusterInstancesRetryWith  %+v", 449, o.Payload)
}

func (o *StopKibanaClusterInstancesRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *StopKibanaClusterInstancesRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-cloud-error-codes
	o.XCloudErrorCodes = response.GetHeader("x-cloud-error-codes")

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
