// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// GetVersionStackReader is a Reader for the GetVersionStack structure.
type GetVersionStackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVersionStackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVersionStackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetVersionStackNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVersionStackOK creates a GetVersionStackOK with default headers values
func NewGetVersionStackOK() *GetVersionStackOK {
	return &GetVersionStackOK{}
}

/*
GetVersionStackOK describes a response with status code 200, with default header values.

The Elastic Stack version is found.
*/
type GetVersionStackOK struct {
	Payload *models.StackVersionConfig
}

// IsSuccess returns true when this get version stack o k response has a 2xx status code
func (o *GetVersionStackOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get version stack o k response has a 3xx status code
func (o *GetVersionStackOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get version stack o k response has a 4xx status code
func (o *GetVersionStackOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get version stack o k response has a 5xx status code
func (o *GetVersionStackOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get version stack o k response a status code equal to that given
func (o *GetVersionStackOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get version stack o k response
func (o *GetVersionStackOK) Code() int {
	return 200
}

func (o *GetVersionStackOK) Error() string {
	return fmt.Sprintf("[GET /stack/versions/{version}][%d] getVersionStackOK  %+v", 200, o.Payload)
}

func (o *GetVersionStackOK) String() string {
	return fmt.Sprintf("[GET /stack/versions/{version}][%d] getVersionStackOK  %+v", 200, o.Payload)
}

func (o *GetVersionStackOK) GetPayload() *models.StackVersionConfig {
	return o.Payload
}

func (o *GetVersionStackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StackVersionConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVersionStackNotFound creates a GetVersionStackNotFound with default headers values
func NewGetVersionStackNotFound() *GetVersionStackNotFound {
	return &GetVersionStackNotFound{}
}

/*
GetVersionStackNotFound describes a response with status code 404, with default header values.

The Elastic Stack version can't be found. (code: `stackpack.version_not_found`)
*/
type GetVersionStackNotFound struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this get version stack not found response has a 2xx status code
func (o *GetVersionStackNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get version stack not found response has a 3xx status code
func (o *GetVersionStackNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get version stack not found response has a 4xx status code
func (o *GetVersionStackNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get version stack not found response has a 5xx status code
func (o *GetVersionStackNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get version stack not found response a status code equal to that given
func (o *GetVersionStackNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get version stack not found response
func (o *GetVersionStackNotFound) Code() int {
	return 404
}

func (o *GetVersionStackNotFound) Error() string {
	return fmt.Sprintf("[GET /stack/versions/{version}][%d] getVersionStackNotFound  %+v", 404, o.Payload)
}

func (o *GetVersionStackNotFound) String() string {
	return fmt.Sprintf("[GET /stack/versions/{version}][%d] getVersionStackNotFound  %+v", 404, o.Payload)
}

func (o *GetVersionStackNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *GetVersionStackNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
