// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package clusters_elasticsearch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewShutdownEsClusterParams creates a new ShutdownEsClusterParams object
// with the default values initialized.
func NewShutdownEsClusterParams() *ShutdownEsClusterParams {
	var (
		hideDefault         = bool(false)
		skipSnapshotDefault = bool(false)
	)
	return &ShutdownEsClusterParams{
		Hide:         &hideDefault,
		SkipSnapshot: &skipSnapshotDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewShutdownEsClusterParamsWithTimeout creates a new ShutdownEsClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShutdownEsClusterParamsWithTimeout(timeout time.Duration) *ShutdownEsClusterParams {
	var (
		hideDefault         = bool(false)
		skipSnapshotDefault = bool(false)
	)
	return &ShutdownEsClusterParams{
		Hide:         &hideDefault,
		SkipSnapshot: &skipSnapshotDefault,

		timeout: timeout,
	}
}

// NewShutdownEsClusterParamsWithContext creates a new ShutdownEsClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewShutdownEsClusterParamsWithContext(ctx context.Context) *ShutdownEsClusterParams {
	var (
		hideDefault         = bool(false)
		skipSnapshotDefault = bool(false)
	)
	return &ShutdownEsClusterParams{
		Hide:         &hideDefault,
		SkipSnapshot: &skipSnapshotDefault,

		Context: ctx,
	}
}

// NewShutdownEsClusterParamsWithHTTPClient creates a new ShutdownEsClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShutdownEsClusterParamsWithHTTPClient(client *http.Client) *ShutdownEsClusterParams {
	var (
		hideDefault         = bool(false)
		skipSnapshotDefault = bool(false)
	)
	return &ShutdownEsClusterParams{
		Hide:         &hideDefault,
		SkipSnapshot: &skipSnapshotDefault,
		HTTPClient:   client,
	}
}

/*ShutdownEsClusterParams contains all the parameters to send to the API endpoint
for the shutdown es cluster operation typically these are written to a http.Request
*/
type ShutdownEsClusterParams struct {

	/*ClusterID
	  The Elasticsearch cluster identifier.

	*/
	ClusterID string
	/*Hide
	  Hides the clusters during shutdown. NOTE: By default, hidden clusters are not listed.

	*/
	Hide *bool
	/*SkipSnapshot
	  When `true`, skips the snapshot when the cluster is shut down.

	*/
	SkipSnapshot *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the shutdown es cluster params
func (o *ShutdownEsClusterParams) WithTimeout(timeout time.Duration) *ShutdownEsClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the shutdown es cluster params
func (o *ShutdownEsClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the shutdown es cluster params
func (o *ShutdownEsClusterParams) WithContext(ctx context.Context) *ShutdownEsClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the shutdown es cluster params
func (o *ShutdownEsClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the shutdown es cluster params
func (o *ShutdownEsClusterParams) WithHTTPClient(client *http.Client) *ShutdownEsClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the shutdown es cluster params
func (o *ShutdownEsClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the shutdown es cluster params
func (o *ShutdownEsClusterParams) WithClusterID(clusterID string) *ShutdownEsClusterParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the shutdown es cluster params
func (o *ShutdownEsClusterParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithHide adds the hide to the shutdown es cluster params
func (o *ShutdownEsClusterParams) WithHide(hide *bool) *ShutdownEsClusterParams {
	o.SetHide(hide)
	return o
}

// SetHide adds the hide to the shutdown es cluster params
func (o *ShutdownEsClusterParams) SetHide(hide *bool) {
	o.Hide = hide
}

// WithSkipSnapshot adds the skipSnapshot to the shutdown es cluster params
func (o *ShutdownEsClusterParams) WithSkipSnapshot(skipSnapshot *bool) *ShutdownEsClusterParams {
	o.SetSkipSnapshot(skipSnapshot)
	return o
}

// SetSkipSnapshot adds the skipSnapshot to the shutdown es cluster params
func (o *ShutdownEsClusterParams) SetSkipSnapshot(skipSnapshot *bool) {
	o.SkipSnapshot = skipSnapshot
}

// WriteToRequest writes these params to a swagger request
func (o *ShutdownEsClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	if o.Hide != nil {

		// query param hide
		var qrHide bool
		if o.Hide != nil {
			qrHide = *o.Hide
		}
		qHide := swag.FormatBool(qrHide)
		if qHide != "" {
			if err := r.SetQueryParam("hide", qHide); err != nil {
				return err
			}
		}

	}

	if o.SkipSnapshot != nil {

		// query param skip_snapshot
		var qrSkipSnapshot bool
		if o.SkipSnapshot != nil {
			qrSkipSnapshot = *o.SkipSnapshot
		}
		qSkipSnapshot := swag.FormatBool(qrSkipSnapshot)
		if qSkipSnapshot != "" {
			if err := r.SetQueryParam("skip_snapshot", qSkipSnapshot); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
