// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package clusters_elasticsearch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// StopEsClusterInstancesReader is a Reader for the StopEsClusterInstances structure.
type StopEsClusterInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopEsClusterInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewStopEsClusterInstancesAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewStopEsClusterInstancesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewStopEsClusterInstancesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 449:
		result := NewStopEsClusterInstancesRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStopEsClusterInstancesAccepted creates a StopEsClusterInstancesAccepted with default headers values
func NewStopEsClusterInstancesAccepted() *StopEsClusterInstancesAccepted {
	return &StopEsClusterInstancesAccepted{}
}

/* StopEsClusterInstancesAccepted describes a response with status code 202, with default header values.

The stop command was issued successfully, use the "GET" command on the /{cluster_id} resource to monitor progress
*/
type StopEsClusterInstancesAccepted struct {
	Payload *models.ClusterCommandResponse
}

func (o *StopEsClusterInstancesAccepted) Error() string {
	return fmt.Sprintf("[POST /clusters/elasticsearch/{cluster_id}/instances/{instance_ids}/_stop][%d] stopEsClusterInstancesAccepted  %+v", 202, o.Payload)
}
func (o *StopEsClusterInstancesAccepted) GetPayload() *models.ClusterCommandResponse {
	return o.Payload
}

func (o *StopEsClusterInstancesAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterCommandResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopEsClusterInstancesForbidden creates a StopEsClusterInstancesForbidden with default headers values
func NewStopEsClusterInstancesForbidden() *StopEsClusterInstancesForbidden {
	return &StopEsClusterInstancesForbidden{}
}

/* StopEsClusterInstancesForbidden describes a response with status code 403, with default header values.

The stop command was prohibited for the given cluster. (code: `clusters.command_prohibited`)
*/
type StopEsClusterInstancesForbidden struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *StopEsClusterInstancesForbidden) Error() string {
	return fmt.Sprintf("[POST /clusters/elasticsearch/{cluster_id}/instances/{instance_ids}/_stop][%d] stopEsClusterInstancesForbidden  %+v", 403, o.Payload)
}
func (o *StopEsClusterInstancesForbidden) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *StopEsClusterInstancesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopEsClusterInstancesNotFound creates a StopEsClusterInstancesNotFound with default headers values
func NewStopEsClusterInstancesNotFound() *StopEsClusterInstancesNotFound {
	return &StopEsClusterInstancesNotFound{}
}

/* StopEsClusterInstancesNotFound describes a response with status code 404, with default header values.

 * The cluster specified by {cluster_id} cannot be found. (code: `clusters.cluster_not_found`)
* One or more of the instances specified at {instance_ids} could not be found. (code: `clusters.instances_not_found`)
*/
type StopEsClusterInstancesNotFound struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *StopEsClusterInstancesNotFound) Error() string {
	return fmt.Sprintf("[POST /clusters/elasticsearch/{cluster_id}/instances/{instance_ids}/_stop][%d] stopEsClusterInstancesNotFound  %+v", 404, o.Payload)
}
func (o *StopEsClusterInstancesNotFound) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *StopEsClusterInstancesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopEsClusterInstancesRetryWith creates a StopEsClusterInstancesRetryWith with default headers values
func NewStopEsClusterInstancesRetryWith() *StopEsClusterInstancesRetryWith {
	return &StopEsClusterInstancesRetryWith{}
}

/* StopEsClusterInstancesRetryWith describes a response with status code 449, with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type StopEsClusterInstancesRetryWith struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

func (o *StopEsClusterInstancesRetryWith) Error() string {
	return fmt.Sprintf("[POST /clusters/elasticsearch/{cluster_id}/instances/{instance_ids}/_stop][%d] stopEsClusterInstancesRetryWith  %+v", 449, o.Payload)
}
func (o *StopEsClusterInstancesRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *StopEsClusterInstancesRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
