// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by go-swagger; DO NOT EDIT.

package platform_infrastructure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/elastic/cloud-sdk-go/pkg/models"
)

// ResyncRunnersReader is a Reader for the ResyncRunners structure.
type ResyncRunnersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResyncRunnersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewResyncRunnersAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 449:
		result := NewResyncRunnersRetryWith()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewResyncRunnersAccepted creates a ResyncRunnersAccepted with default headers values
func NewResyncRunnersAccepted() *ResyncRunnersAccepted {
	return &ResyncRunnersAccepted{}
}

/*
ResyncRunnersAccepted describes a response with status code 202, with default header values.

The ids of documents, organized by model version, that will be synchronized.
*/
type ResyncRunnersAccepted struct {
	Payload *models.ModelVersionIndexSynchronizationResults
}

// IsSuccess returns true when this resync runners accepted response has a 2xx status code
func (o *ResyncRunnersAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this resync runners accepted response has a 3xx status code
func (o *ResyncRunnersAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resync runners accepted response has a 4xx status code
func (o *ResyncRunnersAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this resync runners accepted response has a 5xx status code
func (o *ResyncRunnersAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this resync runners accepted response a status code equal to that given
func (o *ResyncRunnersAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the resync runners accepted response
func (o *ResyncRunnersAccepted) Code() int {
	return 202
}

func (o *ResyncRunnersAccepted) Error() string {
	return fmt.Sprintf("[POST /platform/infrastructure/runners/_resync][%d] resyncRunnersAccepted  %+v", 202, o.Payload)
}

func (o *ResyncRunnersAccepted) String() string {
	return fmt.Sprintf("[POST /platform/infrastructure/runners/_resync][%d] resyncRunnersAccepted  %+v", 202, o.Payload)
}

func (o *ResyncRunnersAccepted) GetPayload() *models.ModelVersionIndexSynchronizationResults {
	return o.Payload
}

func (o *ResyncRunnersAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelVersionIndexSynchronizationResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResyncRunnersRetryWith creates a ResyncRunnersRetryWith with default headers values
func NewResyncRunnersRetryWith() *ResyncRunnersRetryWith {
	return &ResyncRunnersRetryWith{}
}

/*
ResyncRunnersRetryWith describes a response with status code 449, with default header values.

Elevated permissions are required. (code: `root.unauthorized.rbac.elevated_permissions_required`)
*/
type ResyncRunnersRetryWith struct {

	/* The error codes associated with the response
	 */
	XCloudErrorCodes string

	Payload *models.BasicFailedReply
}

// IsSuccess returns true when this resync runners retry with response has a 2xx status code
func (o *ResyncRunnersRetryWith) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resync runners retry with response has a 3xx status code
func (o *ResyncRunnersRetryWith) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resync runners retry with response has a 4xx status code
func (o *ResyncRunnersRetryWith) IsClientError() bool {
	return true
}

// IsServerError returns true when this resync runners retry with response has a 5xx status code
func (o *ResyncRunnersRetryWith) IsServerError() bool {
	return false
}

// IsCode returns true when this resync runners retry with response a status code equal to that given
func (o *ResyncRunnersRetryWith) IsCode(code int) bool {
	return code == 449
}

// Code gets the status code for the resync runners retry with response
func (o *ResyncRunnersRetryWith) Code() int {
	return 449
}

func (o *ResyncRunnersRetryWith) Error() string {
	return fmt.Sprintf("[POST /platform/infrastructure/runners/_resync][%d] resyncRunnersRetryWith  %+v", 449, o.Payload)
}

func (o *ResyncRunnersRetryWith) String() string {
	return fmt.Sprintf("[POST /platform/infrastructure/runners/_resync][%d] resyncRunnersRetryWith  %+v", 449, o.Payload)
}

func (o *ResyncRunnersRetryWith) GetPayload() *models.BasicFailedReply {
	return o.Payload
}

func (o *ResyncRunnersRetryWith) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-cloud-error-codes
	hdrXCloudErrorCodes := response.GetHeader("x-cloud-error-codes")

	if hdrXCloudErrorCodes != "" {
		o.XCloudErrorCodes = hdrXCloudErrorCodes
	}

	o.Payload = new(models.BasicFailedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
